### ISSUE TITLE
Build errors for release 1.0

### ISSUE THREAD

**Issue by gpbenton** [fbarthelery/geekttrss#1] opened 2018-11-29 16:45 UTC
I am getting the following errors when building 1.0.  It is probably a configuration thing, but I am using the latest android sdk 28 so I am wondering which to change to, or how to change the current configuration.

> Kotlin plugin is applied to the project :app but we cannot find the KaptTask. Make sure you apply the kotlin-kapt plugin because it is necessary to use kotlin with data binding.
> e: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor

**Comment by fbarthelery** [comment] 2018-11-29 18:53
I can't reproduce your error. Can you send the whole console log ?

**Comment by gpbenton** [comment] 2018-11-30 09:50
Log is in attached file


[geekttrss.log](https://github.com/fbarthelery/geekttrss/files/2632761/geekttrss.log)

**Comment by gpbenton** [comment] 2018-12-01 08:52
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Its probably something like that, I think I'll set up a virtual machine rather than mess around with my rather stock Kubuntu desktop.

**Comment by fbarthelery** [comment] 2018-12-18 20:31
I just released version 1.1.0 so I'm going to close this issue. Unfortunatelly it's not totally resolved but building Android application with a JDK > 8 is out of my power.

**Closed by fbarthelery** 2018-12-18 20:31 UTC
