### ISSUE TITLE
FR: headline-only view mode

### ISSUE THREAD

**Issue by abliss** [fbarthelery/geekttrss#14] opened 2020-07-25 18:47 UTC
Maybe I'm unique in this, but among my feeds, 90% or more of the articles are not interesting to me, so I like to quickly skim past the headlines and only expand the ones that look good.

**Comment by fbarthelery** [comment] 2023-06-01 23:24
I'm closing this as a duplicate of #26.

**Closed by fbarthelery** 2023-06-01 23:24 UTC
